version: '3.3'

services:
  proxy:
    build: docker/proxy
    ports:
      - 80:80

  proxy_web:
    build:
      args:
        NODE_ENV: production
      context: .
    environment:
      PORT: 80
    expose:
      - 80
    ports:
      - 80

  web:
    build:
      args:
        NODE_ENV: production
      context: .
      dockerfile: docker/full/Dockerfile
    ports:
      - 3000:3000
